// Build pipeline for @oddsrabbit/apps-sdk.
// Produces:
//   - dist/sdk-v1.js       IIFE bundle for CDN script tag (minified, auto-installs window.OddsRabbit)
//   - dist/sdk-v1.esm.js   ESM bundle for npm consumers
//   - dist/sdk-v1.cjs      CJS bundle for legacy Node consumers
//   - dist/schemas.*       Same three formats for the schemas-only export
//   - dist/leaderboard-v1.js   IIFE bundle for CDN script tag (installs window.OddsRabbitUI)
//   - dist/leaderboard-v1.esm.js + .css   Shared leaderboard UI for bundler consumers
//   - dist/host/           Sandbox host page (index.html, host.js, host.css)
//   - dist/**/*.d.ts       TypeScript declarations (via tsc) + thin wrappers for stable entry paths

import * as esbuild from 'esbuild';
import { copyFile, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { execSync } from 'node:child_process';
import { createHash } from 'node:crypto';

const watch = process.argv.includes('--watch');

// Cache-bust ID stamped into every HTML reference to JS/CSS. Each `npm run
// build` produces a fresh ID, so deployed HTML points at unique URLs and
// browsers can't serve stale JS/CSS even if the file paths haven't changed.
// The HTML files themselves still need a short cache TTL (configured at the
// CDN layer) so the new IDs reach clients.
const BUILD_ID = process.env.BUILD_ID || String(Date.now());

// Separate cache-bust token for the SHARED `sdk-v1.js`, which every game's
// index.html loads. Using BUILD_ID for it is fragile: a game stamps its OWN
// build id, so when the SDK changes you must rebuild + redeploy every game (and
// any game still on an old id keeps loading the cached old SDK). Instead we
// stamp the SDK reference with a hash of the SDK's CONTENT (`__SDK_VERSION__`):
// the URL changes iff the SDK actually changes, so all games bust together and
// stay cached otherwise — and the public `sdk-v1.js` filename stays stable.
// Computed from dist/sdk-v1.js after the bundle is built (see computeSdkVersion).
let SDK_VERSION = BUILD_ID;

// Same treatment for the shared leaderboard UI (`__UI_VERSION__`), which the
// vanilla games load as a second script tag alongside the SDK. Hashed over the
// JS *and* the CSS together: they are one component and always ship as a pair,
// so a token that moved for only one of them would let a game pick up new
// markup against cached styles.
let UI_VERSION = BUILD_ID;

// Per-build cache policy, dropped into dist/ so it travels with every manual
// upload (Apache reads .htaccess from the served directory tree — no separate
// server access needed each deploy).
//
// The cache-bust scheme only works if the HTML is ALWAYS revalidated: every
// asset ref carries `?v=<BUILD_ID>`, so a new build makes the HTML point at new
// URLs — but only if browsers actually re-fetch the HTML. Serving HTML with a
// long max-age (the bug this fixes: index.html was `max-age=31536000`) freezes
// returning users on whatever build they first loaded, even after the asset
// files are replaced on disk. So: HTML = no-cache; versioned assets = immutable.
//
// nginx origins ignore .htaccess — see README/deploy notes for the equivalent
// `location` block.
const APPS_HTACCESS = `# Generated by build.config.mjs — do not edit by hand.
# Cache policy for the OddsRabbit apps bundle.
<IfModule mod_headers.c>
  # HTML entry points: always revalidate so new ?v= build IDs reach clients.
  <FilesMatch "\\.html$">
    Header set Cache-Control "no-cache, must-revalidate, max-age=0"
  </FilesMatch>

  # Versioned static assets (every ref carries ?v=<build id>): cache hard.
  <FilesMatch "\\.(js|css|woff2|png)$">
    Header set Cache-Control "public, max-age=31536000, immutable"
  </FilesMatch>

  # Source maps are referenced without ?v= (via sourceMappingURL); revalidate
  # so devtools never load a stale map after a rebuild.
  <FilesMatch "\\.map$">
    Header set Cache-Control "no-cache, must-revalidate, max-age=0"
  </FilesMatch>
</IfModule>
`;

// Game files for the vanilla-JS 2048 port. Game logic JS is copied verbatim;
// only index.html carries the __BUILD_ID__ placeholder.
const GAME_2048_JS = [
  'keyboard_input_manager.js',
  'html_actuator.js',
  'grid.js',
  'tile.js',
  'storage_manager.js',
  'game_manager.js',
  'application.js',
  'leaderboard.js',
];

// Game files for the vanilla-JS Snake game. Same shape as 2048 — vanilla JS
// copied verbatim, only index.html carries the __BUILD_ID__ placeholder.
const GAME_SNAKE_JS = [
  'input_manager.js',
  'storage_manager.js',
  'game.js',
  'renderer.js',
  'application.js',
];

// Match-3 (Fruit Match). Same drop-in pattern as snake: vanilla JS copied
// verbatim, only index.html carries the __BUILD_ID__ placeholder.
const GAME_MATCH3_JS = [
  'input_manager.js',
  'storage_manager.js',
  'game.js',
  'renderer.js',
  'sound_manager.js',
  'application.js',
];

// Solitaire. Original Klondike. Splits deck/rules out of game.js since
// solitaire has materially more rules logic than the action games.
const GAME_SOLITAIRE_JS = [
  'input_manager.js',
  'storage_manager.js',
  'sound_manager.js',
  'deck.js',
  'solver.js',
  'game.js',
  'renderer.js',
  'application.js',
];

await rm('dist', { recursive: true, force: true });
await mkdir('dist/host', { recursive: true });
await mkdir('dist/rabbit-words', { recursive: true });
await mkdir('dist/rabbit-globe', { recursive: true });
await mkdir('dist/2048/js', { recursive: true });
await mkdir('dist/snake/js', { recursive: true });
await mkdir('dist/snake/fonts', { recursive: true });
await mkdir('dist/snake/images', { recursive: true });
await mkdir('dist/match3/js', { recursive: true });
await mkdir('dist/solitaire/js', { recursive: true });
await mkdir('dist/solitaire/fonts', { recursive: true });
await mkdir('dist/liquid/js', { recursive: true });

const baseOpts = {
  bundle: true,
  target: ['es2020'],
  sourcemap: true,
  logLevel: 'info',
};

const browserOpts = { ...baseOpts, platform: 'browser' };
const neutralOpts = { ...baseOpts, platform: 'neutral' };

const buildTargets = [
  // Bridge SDK
  {
    ...browserOpts,
    entryPoints: ['src/sdk/index.ts'],
    outfile: 'dist/sdk-v1.js',
    format: 'iife',
    globalName: '__OddsRabbitSDK',
    minify: true,
  },
  {
    ...browserOpts,
    entryPoints: ['src/sdk/index.ts'],
    outfile: 'dist/sdk-v1.esm.js',
    format: 'esm',
  },
  {
    ...neutralOpts,
    entryPoints: ['src/sdk/index.ts'],
    outfile: 'dist/sdk-v1.cjs',
    format: 'cjs',
  },
  // Schemas (single source of truth, exported separately for backend tooling / docs site)
  {
    ...browserOpts,
    entryPoints: ['src/schemas/index.ts'],
    outfile: 'dist/schemas.esm.js',
    format: 'esm',
  },
  {
    ...neutralOpts,
    entryPoints: ['src/schemas/index.ts'],
    outfile: 'dist/schemas.cjs',
    format: 'cjs',
  },
  // Shared leaderboard UI. Deliberately a separate bundle rather than part of
  // sdk-v1.js: every game loads the SDK, but only the four with boards need
  // this, and a transport library should not carry DOM rendering.
  {
    ...browserOpts,
    entryPoints: ['src/ui/index.ts'],
    outfile: 'dist/leaderboard-v1.js',
    format: 'iife',
    globalName: '__OddsRabbitUI',
    minify: true,
  },
  {
    ...browserOpts,
    entryPoints: ['src/ui/index.ts'],
    outfile: 'dist/leaderboard-v1.esm.js',
    format: 'esm',
  },
  // Sandbox host page
  {
    ...browserOpts,
    entryPoints: ['src/host/host.ts'],
    outfile: 'dist/host/host.js',
    format: 'iife',
    minify: true,
  },
  // RabbitWords — reference game
  {
    ...browserOpts,
    entryPoints: ['rabbit-words/src/main.ts'],
    outfile: 'dist/rabbit-words/main.js',
    format: 'esm',
    minify: true,
  },
  // RabbitGlobe — daily photo-pin geo-guess game (bundles Leaflet)
  {
    ...browserOpts,
    entryPoints: ['rabbit-globe/src/main.ts'],
    outfile: 'dist/rabbit-globe/main.js',
    format: 'esm',
    minify: true,
  },
];

if (watch) {
  // Watch mode: rebuild on source change. TS declarations are NOT regenerated in watch
  // (run `npm run build` for a full release build).
  const contexts = await Promise.all(buildTargets.map((opts) => esbuild.context(opts)));
  await Promise.all(contexts.map((ctx) => ctx.watch()));
  await copyHostAssets();
  console.log('Watching for changes (Ctrl+C to stop)...');
} else {
  await Promise.all(buildTargets.map((opts) => esbuild.build(opts)));
  await copyHostAssets();
  generateDeclarations();
  console.log('Build complete.');
}

async function copyHostAssets() {
  // The SDK bundle exists by now (built before this runs), so hash it for the
  // `__SDK_VERSION__` cache-bust stamped into every game's index.html.
  SDK_VERSION = await computeSdkVersion();
  // The leaderboard CSS has to land before the version is hashed over it.
  await copyFile('src/ui/leaderboard.css', 'dist/leaderboard-v1.css');
  UI_VERSION = await computeUiVersion();
  await Promise.all([
    writeFile('dist/.htaccess', APPS_HTACCESS),
    copyHtmlWithBuildId('src/host/host.html', 'dist/host/index.html'),
    copyFile('src/host/host.css', 'dist/host/host.css'),
    copyHtmlWithBuildId('rabbit-words/index.html', 'dist/rabbit-words/index.html'),
    copyFile('rabbit-words/styles.css', 'dist/rabbit-words/styles.css'),
    // RabbitGlobe — geo-guess game. Ships Leaflet's stylesheet alongside ours.
    copyHtmlWithBuildId('rabbit-globe/index.html', 'dist/rabbit-globe/index.html'),
    copyFile('rabbit-globe/styles.css', 'dist/rabbit-globe/styles.css'),
    copyFile('node_modules/leaflet/dist/leaflet.css', 'dist/rabbit-globe/leaflet.css'),
    copyHtmlWithBuildId('2048/index.html', 'dist/2048/index.html'),
    copyFile('2048/styles.css', 'dist/2048/styles.css'),
    ...GAME_2048_JS.map((name) =>
      copyFile(`2048/js/${name}`, `dist/2048/js/${name}`)
    ),
    // Snake — original implementation, vanilla JS, no bundling needed.
    copyHtmlWithBuildId('snake/index.html', 'dist/snake/index.html'),
    copyFile('snake/styles.css', 'dist/snake/styles.css'),
    ...GAME_SNAKE_JS.map((name) =>
      copyFile(`snake/js/${name}`, `dist/snake/js/${name}`)
    ),
    // Press Start 2P (OFL 1.1, latin subset). OFL.txt ships alongside the
    // woff2 so the redistributed font carries its license, as required.
    copyFile('snake/fonts/press-start-2p-latin.woff2', 'dist/snake/fonts/press-start-2p-latin.woff2'),
    copyFile('snake/fonts/OFL.txt', 'dist/snake/fonts/OFL.txt'),
    // Snake-head sprite — the OddsRabbit "karat" rabbit icon (the in-app
    // currency mark) reused as the snake's face. 32x32 PNG with palette
    // transparency so the green body shows through around the rabbit shape.
    copyFile('snake/images/head.png', 'dist/snake/images/head.png'),
    // Match-3 (Fruit Match). Same drop-in pattern as snake.
    copyHtmlWithBuildId('match3/index.html', 'dist/match3/index.html'),
    copyFile('match3/styles.css', 'dist/match3/styles.css'),
    ...GAME_MATCH3_JS.map((name) =>
      copyFile(`match3/js/${name}`, `dist/match3/js/${name}`)
    ),
    // Solitaire. Reuses snake's Press Start 2P font — the OFL.txt ships
    // alongside it so the redistributed font carries its license.
    copyHtmlWithBuildId('solitaire/index.html', 'dist/solitaire/index.html'),
    copyFile('solitaire/styles.css', 'dist/solitaire/styles.css'),
    ...GAME_SOLITAIRE_JS.map((name) =>
      copyFile(`solitaire/js/${name}`, `dist/solitaire/js/${name}`)
    ),
    copyFile('snake/fonts/press-start-2p-latin.woff2', 'dist/solitaire/fonts/press-start-2p-latin.woff2'),
    copyFile('snake/fonts/OFL.txt', 'dist/solitaire/fonts/OFL.txt'),
    // Liquid — WebGL fluid simulation. Vendored vanilla JS, no bundling needed.
    copyHtmlWithBuildId('liquid/index.html', 'dist/liquid/index.html'),
    copyFile('liquid/js/script.js', 'dist/liquid/js/script.js'),
    copyFile('liquid/js/dat.gui.min.js', 'dist/liquid/js/dat.gui.min.js'),
    copyFile('liquid/js/bootstrap.js', 'dist/liquid/js/bootstrap.js'),
  ]);
}

// Substitutes cache-bust placeholders in HTML:
//   __BUILD_ID__     — per-build id, for the game's OWN assets (main.js, css).
//   __SDK_VERSION__  — content hash of the shared sdk-v1.js (see SDK_VERSION).
//   __UI_VERSION__   — content hash of the shared leaderboard-v1.js + .css.
async function copyHtmlWithBuildId(src, dest) {
  const content = await readFile(src, 'utf8');
  await writeFile(
    dest,
    content
      .replaceAll('__BUILD_ID__', BUILD_ID)
      .replaceAll('__SDK_VERSION__', SDK_VERSION)
      .replaceAll('__UI_VERSION__', UI_VERSION)
  );
}

// Short content hash of the built SDK bundle. Falls back to BUILD_ID when the
// file isn't present yet (e.g. the first pass of `--watch` before esbuild has
// emitted it) — a stale stamp in dev is harmless since there's no CDN there.
async function computeSdkVersion() {
  try {
    const buf = await readFile('dist/sdk-v1.js');
    return createHash('sha256').update(buf).digest('hex').slice(0, 12);
  } catch {
    return BUILD_ID;
  }
}

// Content hash over the leaderboard bundle AND its stylesheet, so the two can
// never be versioned apart. Same watch-mode fallback as computeSdkVersion.
async function computeUiVersion() {
  try {
    const [js, css] = await Promise.all([
      readFile('dist/leaderboard-v1.js'),
      readFile('dist/leaderboard-v1.css'),
    ]);
    return createHash('sha256').update(js).update(css).digest('hex').slice(0, 12);
  } catch {
    return BUILD_ID;
  }
}

function generateDeclarations() {
  // tsc emits to dist/<rootDir-mirror>/, e.g. dist/sdk/index.d.ts. Wrap with stable entries.
  execSync('tsc --emitDeclarationOnly --outDir dist', { stdio: 'inherit' });
}

// After tsc, write thin wrappers so package.json `types` paths stay stable as the SDK evolves.
if (!watch) {
  await writeFile('dist/sdk-v1.d.ts', "export * from './sdk/index';\n");
  await writeFile('dist/schemas.d.ts', "export * from './schemas/index';\n");
  await writeFile('dist/leaderboard-v1.d.ts', "export * from './ui/index';\n");
}
